export const dummyStockList = [
    {  value : 1,  id: 1, label: "Apple Inc. (AAPL)" },
    {  value : 2,  id: 2, label: "Microsoft Corporation (MSFT)" },
    {  value : 3,  id: 3, label: "Amazon.com, Inc. (AMZN)" },
    {  value : 4,  id: 4, label: "Tesla, Inc. (TSLA)" },
    {  value : 5,  id: 5, label: "Alphabet Inc. (GOOGL)" },
    {  value : 6,  id: 6, label: "Meta Platforms, Inc. (META)" },
    {  value : 7,  id: 7, label: "NVIDIA Corporation, Corporation (NVDA)" },
    {  value : 8,  id: 8, label: "Netflix, Inc. (NFLX)" },
    {  value : 9,  id: 9, label: "Berkshire Hathaway Inc. (BRK.A)" },
    {  value : 10,  id: 10, label: "Johnson & Johnson (JNJ)" },
    {  value : 11,  id: 11, label: "Visa Inc. (V)" },
    {  value : 12,  id: 12, label: "Walmart Inc. (WMT)" },
    {  value : 13,  id: 13, label: "JPMorgan Chase & Co. (JPM)" },
    {  value : 14,  id: 14, label: "Procter & Gamble Co. (PG)" },
    {  value : 15,  id: 15, label: "Intel Corporation (INTC)" },
  ];